name: Linux CI

on:
  workflow_call:
    inputs:
      os:
        description: 'The linux versions to execute the job on'
        required: false
        type: string
        default: '["ubuntu-latest", "ubuntu-22.04", "ubuntu-20.04"]'
      build_modes:
        description: 'The build modes to execute the job on'
        required: false
        type: string
        default: '["debug", "release"]'
      swift_versions:
        description: 'The swift versions to execute the job on'
        required: false
        type: string
        default: '["6.0", "5.10", "5.9", "5.8", "5.7"]'
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_PUBLIC_KEY:
        required: true

jobs:
  build_linux:
    strategy:
      matrix:
        os: ${{ fromJSON(github.event.inputs.os) }}
        swift: ${{ fromJSON(github.event.inputs.swift_versions) }}
        build_mode: ${{ fromJSON(github.event.inputs.build_modes) }}
    name: Swift ${{ matrix.swift }} ${{ matrix.build_mode }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: slashmo/install-swift@v0.4.0
        with:
          version: ${{ matrix.swift }}

      - name: Setup SSH Key
        run: | 
          rm -rf ~/.ssh
          mkdir -m 0700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          chmod 0600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Checkout repo
        uses: actions/checkout@v4
      
      #- name: Reconfigure Private Repo URLs
      #  run: sed -i 's/git@github.com:/https:\/\/${{ secrets.ACCESS_TOKEN }}@github.com\//g' Package.swift

      - name: build
        run: swift build -c ${{ matrix.build_mode }}

      - name: Test
        run: swift test -c ${{ matrix.build_mode }}

  ci-linux-report:
    runs-on: ubuntu-latest
    needs: build_linux
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
