name: Swift Coverage Test

on:
  workflow_call:
      inputs:
        MINIMUM_COVERAGE:
          required: true
          description: 'The minimum code coverage percentage required (0 - 100).'
          type: number
      secrets:
        SSH_PRIVATE_KEY:
          required: true
        SSH_PUBLIC_KEY:
          required: true

jobs:

  exec-cov:
    runs-on: ubuntu-latest

    steps:
      - uses: slashmo/install-swift@v0.4.0
        with:
          version: "5.10"

      - name: Setup SSH Key
        run: | 
            rm -rf ~/.ssh
            mkdir -m 0700 ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
            chmod 0600 ~/.ssh/id_ed25519
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_ed25519

      - name: Checkout repo
        uses: actions/checkout@v4

      #- name: Reconfigure Private Repo URLs
      #  run: sed -i 's/git@github.com:/https:\/\/${{ secrets.ACCESS_TOKEN }}@github.com\//g' Package.swift

      - name: Run tests
        run: swift test --enable-code-coverage

      - name: Coverage Test
        uses: mattpolzin/swift-codecov-action@0.7.3
        id: cov
        with:
          MINIMUM_COVERAGE: ${{ inputs.MINIMUM_COVERAGE }}

      - name: Post Positive Result
        if: ${{ success() }}
        run: |
          echo "::warning file=Package.swift,line=1,col=1::The current code coverage percentage is passing with ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.outputs.minimum_coverage }}%)."

      - name: Post Negative Result
        if: ${{ failure() }}
        run: |
          echo "::error file=Package.swift,line=1,col=1::The current code coverage percentage is failing with ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.outputs.minimum_coverage }}%)."
