name: Swift Lint 

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_PUBLIC_KEY:
        required: true

jobs:

  swiftlint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo 
        uses: actions/checkout@v4

      #- name: Reconfigure Private Repo URLs
      #  run: sed -i 's/git@github.com:/https:\/\/${{ secrets.ACCESS_TOKEN }}@github.com\//g' Package.swift
      
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
            args: --strict

  swiftformat:
    runs-on: ubuntu-latest
    steps:
      - uses: slashmo/install-swift@v0.4.0
        with:
          version: "5.10"

      - name: Install swift-format
        uses: mipalgu/install-swift-format@main
        with:
          ref: '510.1.0'

      - name: Setup SSH Key
        run: | 
          rm -rf ~/.ssh
          mkdir -m 0700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          chmod 0600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Clone Repo
        uses: actions/checkout@v4

      - name: SwiftFormat
        run: swift-format lint -rs --configuration .swiftformat.json Sources Tests
  
  swiftlint-report:
    runs-on: ubuntu-latest
    needs: [swiftlint, swiftformat]
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
