name: Swift Lint 

on:
  workflow_call:

jobs:

  swiftlint:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone Repo 
        uses: actions/checkout@v4

      #- name: Reconfigure Private Repo URLs
      #  run: sed -i 's/git@github.com:/https:\/\/${{ secrets.ACCESS_TOKEN }}@github.com\//g' Package.swift
      
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
            args: --strict
